Change LDLIBS order because of build problem
One customer had a build problem with linking libuv on

    Linux ubuntu 3.8.0-29-generic #42~precise1-Ubuntu SMP
    Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

which is fixed by changing the order to that rt is linked after
libuv. This works fine on my Linux as well:

    Linux ubuntu 3.13.0-27-generic #50-Ubuntu SMP
    Thu May 15 18:06:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

The error looks like

    keyserver-20140603/tmp/libuv-1daff47ae9df55902f07d3c5b8a3a393306a2f1e/
    src/unix/linux-core.c:454: undefined reference to `clock_gettime'
    collect2: ld returned 1 exit status

when it occurs.